
package br.gov.caixa.sibar.consulta_saldo.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Consulta_Saldo", targetNamespace = "http://caixa.gov.br/sibar/consulta_saldo/ws", wsdlLocation = "http://des.barramento.caixa/sibar/ConsultaSaldo?wsdl")
public class ConsultaSaldo_Service
    extends Service
{

    private final static URL CONSULTASALDO_WSDL_LOCATION;
    private final static WebServiceException CONSULTASALDO_EXCEPTION;
    private final static QName CONSULTASALDO_QNAME = new QName("http://caixa.gov.br/sibar/consulta_saldo/ws", "Consulta_Saldo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://des.barramento.caixa/sibar/ConsultaSaldo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTASALDO_WSDL_LOCATION = url;
        CONSULTASALDO_EXCEPTION = e;
    }

    public ConsultaSaldo_Service() {
        super(__getWsdlLocation(), CONSULTASALDO_QNAME);
    }

    public ConsultaSaldo_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTASALDO_QNAME, features);
    }

    public ConsultaSaldo_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTASALDO_QNAME);
    }

    public ConsultaSaldo_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTASALDO_QNAME, features);
    }

    public ConsultaSaldo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaSaldo_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaSaldo
     */
    @WebEndpoint(name = "Consulta_SaldoSOAP")
    public ConsultaSaldo getConsultaSaldoSOAP() {
        return super.getPort(new QName("http://caixa.gov.br/sibar/consulta_saldo/ws", "Consulta_SaldoSOAP"), ConsultaSaldo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaSaldo
     */
    @WebEndpoint(name = "Consulta_SaldoSOAP")
    public ConsultaSaldo getConsultaSaldoSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://caixa.gov.br/sibar/consulta_saldo/ws", "Consulta_SaldoSOAP"), ConsultaSaldo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTASALDO_EXCEPTION!= null) {
            throw CONSULTASALDO_EXCEPTION;
        }
        return CONSULTASALDO_WSDL_LOCATION;
    }

}
