
package br.gov.caixa.sibar.consulta_saldo.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import br.gov.caixa.sibar.consulta_saldo.ServicoEntradaNegocialType;
import br.gov.caixa.sibar.consulta_saldo.ServicoSaidaNegocialType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Consulta_Saldo", targetNamespace = "http://caixa.gov.br/sibar/consulta_saldo/ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.gov.caixa.sibar.ObjectFactory.class,
    br.gov.caixa.sibar.consulta_saldo.ObjectFactory.class
})
public interface ConsultaSaldo {


    /**
     * 
     * @param parameters
     * @return
     *     returns br.gov.caixa.sibar.consulta_saldo.ServicoSaidaNegocialType
     */
    @WebMethod(operationName = "CONSULTA_SALDO", action = "ConsultaSaldo")
    @WebResult(name = "SERVICO_SAIDA", targetNamespace = "http://caixa.gov.br/sibar/consulta_saldo", partName = "parameters")
    public ServicoSaidaNegocialType consultaSALDO(
        @WebParam(name = "SERVICO_ENTRADA", targetNamespace = "http://caixa.gov.br/sibar/consulta_saldo", partName = "parameters")
        ServicoEntradaNegocialType parameters);

}
