-- Exemplo de Insert, onde a tabela ja tem uma sequence definida
INSERT INTO OFB.OFBTB004_CONTA (NU_AGENCIA,NU_OPERACAO_PRODUTO,NU_CONTA,DV_CONTA,IC_NSGD,VR_SALDO_CONTA) VALUES(0013,1288,1122,7,1,0.0);
-- Exemplos para ver o valor atual de uma sequence
SELECT OFB.OFBSQ001_NU_GRUPO_ACESSO.CURRVAL;
SELECT OFB.OFBSQ004_NU_NSU_CONTA.CURRVAL;

-- Mostra as definicoes de uma tabela
SHOW COLUMNS FROM OFB.OFBTB001_GRUPO_ACESSO;
SHOW COLUMNS FROM OFB.OFBTB002_USUARIO;
SHOW COLUMNS FROM OFB.OFBTB003_CLIENTE;
SHOW COLUMNS FROM OFB.OFBTB004_CONTA;
SHOW COLUMNS FROM OFB.OFBTB005_CLIENTE_CONTA;

-- Exemplo Deleta Registro
DELETE FROM OFB.OFBTB004_CONTA WHERE NU_NSU_CONTA = 8;