package br.gov.caixa.ptdes.entity;
// Generated 30/10/2018 21:04:33 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ofbtb004Conta generated by hbm2java
 */
@Entity
@Table(name = "OFBTB004_CONTA", schema = "OFB", catalog = "OVERDB", uniqueConstraints = @UniqueConstraint(columnNames = {
		"NU_AGENCIA", "NU_OPERACAO_PRODUTO", "NU_CONTA" }))
public class Ofbtb004Conta implements java.io.Serializable {

	private Long nuNsuConta;
	private short nuAgencia;
	private short nuOperacaoProduto;
	private long nuConta;
	private byte dvConta;
	private byte icNsgd;
	private BigDecimal vrSaldoConta;
	private Set<Ofbtb003Cliente> ofbtb003Clientes = new HashSet<Ofbtb003Cliente>(0);

	public Ofbtb004Conta() {
	}

	public Ofbtb004Conta(short nuAgencia, short nuOperacaoProduto, long nuConta, byte dvConta, byte icNsgd,
			BigDecimal vrSaldoConta) {
		this.nuAgencia = nuAgencia;
		this.nuOperacaoProduto = nuOperacaoProduto;
		this.nuConta = nuConta;
		this.dvConta = dvConta;
		this.icNsgd = icNsgd;
		this.vrSaldoConta = vrSaldoConta;
	}

	public Ofbtb004Conta(short nuAgencia, short nuOperacaoProduto, long nuConta, byte dvConta, byte icNsgd,
			BigDecimal vrSaldoConta, Set<Ofbtb003Cliente> ofbtb003Clientes) {
		this.nuAgencia = nuAgencia;
		this.nuOperacaoProduto = nuOperacaoProduto;
		this.nuConta = nuConta;
		this.dvConta = dvConta;
		this.icNsgd = icNsgd;
		this.vrSaldoConta = vrSaldoConta;
		this.ofbtb003Clientes = ofbtb003Clientes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@SequenceGenerator(name = "conta_gen", schema = "OFB", sequenceName = "OFBSQ004_NU_NSU_CONTA", initialValue = 1, allocationSize = 0)
	@Column(name = "NU_NSU_CONTA", unique = true, nullable = false, precision = 15, scale = 0, columnDefinition="DECIMAL(15)")
	public Long getNuNsuConta() {
		return this.nuNsuConta;
	}

	public void setNuNsuConta(Long nuNsuConta) {
		this.nuNsuConta = nuNsuConta;
	}

	@Column(name = "NU_AGENCIA", nullable = false, precision = 4, scale = 0, columnDefinition="DECIMAL(4)")
	public short getNuAgencia() {
		return this.nuAgencia;
	}

	public void setNuAgencia(short nuAgencia) {
		this.nuAgencia = nuAgencia;
	}

	@Column(name = "NU_OPERACAO_PRODUTO", nullable = false, precision = 4, scale = 0, columnDefinition="DECIMAL(4)")
	public short getNuOperacaoProduto() {
		return this.nuOperacaoProduto;
	}

	public void setNuOperacaoProduto(short nuOperacaoProduto) {
		this.nuOperacaoProduto = nuOperacaoProduto;
	}

	@Column(name = "NU_CONTA", nullable = false, precision = 12, scale = 0, columnDefinition="DECIMAL(12)")
	public long getNuConta() {
		return this.nuConta;
	}

	public void setNuConta(long nuConta) {
		this.nuConta = nuConta;
	}

	@Column(name = "DV_CONTA", nullable = false, precision = 2, scale = 0, columnDefinition="DECIMAL(2)")
	public byte getDvConta() {
		return this.dvConta;
	}

	public void setDvConta(byte dvConta) {
		this.dvConta = dvConta;
	}

	@Column(name = "IC_NSGD", nullable = false, precision = 2, scale = 0, columnDefinition="DECIMAL(2)")
	public byte getIcNsgd() {
		return this.icNsgd;
	}

	public void setIcNsgd(byte icNsgd) {
		this.icNsgd = icNsgd;
	}

	@Column(name = "VR_SALDO_CONTA", nullable = false, precision = 15, columnDefinition="DECIMAL(15)")
	public BigDecimal getVrSaldoConta() {
		return this.vrSaldoConta;
	}

	public void setVrSaldoConta(BigDecimal vrSaldoConta) {
		this.vrSaldoConta = vrSaldoConta;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "OFBTB005_CLIENTE_CONTA", schema = "OFB", catalog = "OVERDB", joinColumns = {
			@JoinColumn(name = "NU_NSU_CONTA_004", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "NU_CPF_CLIENTE_003", nullable = false, updatable = false) })
	public Set<Ofbtb003Cliente> getOfbtb003Clientes() {
		return this.ofbtb003Clientes;
	}

	public void setOfbtb003Clientes(Set<Ofbtb003Cliente> ofbtb003Clientes) {
		this.ofbtb003Clientes = ofbtb003Clientes;
	}

	@Override
	public String toString() {
		return "Ofbtb004Conta [nuNsuConta=" + nuNsuConta + ", nuAgencia=" + nuAgencia + ", nuOperacaoProduto="
				+ nuOperacaoProduto + ", nuConta=" + nuConta + ", dvConta=" + dvConta + ", icNsgd=" + icNsgd
				+ ", vrSaldoConta=" + vrSaldoConta + "]";
	}	
	
}
