package br.gov.caixa.ptdes.entity;
// Generated 30/10/2018 21:04:33 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ofbtb002Usuario generated by hbm2java
 */
@Entity
@Table(name = "OFBTB002_USUARIO", schema = "OFB", catalog = "OVERDB")
public class Ofbtb002Usuario implements java.io.Serializable {

	private String noUsuario;
	private Ofbtb001GrupoAcesso ofbtb001GrupoAcesso;
	private String deSenha;

	public Ofbtb002Usuario() {
	}

	public Ofbtb002Usuario(String noUsuario, Ofbtb001GrupoAcesso ofbtb001GrupoAcesso, String deSenha) {
		this.noUsuario = noUsuario;
		this.ofbtb001GrupoAcesso = ofbtb001GrupoAcesso;
		this.deSenha = deSenha;
	}

	@Id

	@Column(name = "NO_USUARIO", unique = true, nullable = false, length = 7)
	public String getNoUsuario() {
		return this.noUsuario;
	}

	public void setNoUsuario(String noUsuario) {
		this.noUsuario = noUsuario;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "NU_GRUPO_ACESSO", nullable = false)
	public Ofbtb001GrupoAcesso getOfbtb001GrupoAcesso() {
		return this.ofbtb001GrupoAcesso;
	}

	public void setOfbtb001GrupoAcesso(Ofbtb001GrupoAcesso ofbtb001GrupoAcesso) {
		this.ofbtb001GrupoAcesso = ofbtb001GrupoAcesso;
	}

	@Column(name = "DE_SENHA", nullable = false, length = 200)
	public String getDeSenha() {
		return this.deSenha;
	}

	public void setDeSenha(String deSenha) {
		this.deSenha = deSenha;
	}

	@Override
	public String toString() {
		return "Ofbtb002Usuario [noUsuario=" + noUsuario + ", deSenha="	+ deSenha + "]";
	}
	
}
