package br.gov.caixa.ptdes.entity;
// Generated 30/10/2018 21:04:33 by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ofbtb001GrupoAcesso generated by hbm2java
 */
@Entity
@Table(name = "OFBTB001_GRUPO_ACESSO", schema = "OFB", catalog = "OVERDB", uniqueConstraints = @UniqueConstraint(columnNames = "NO_GRUPO_ACESSO"))
public class Ofbtb001GrupoAcesso implements java.io.Serializable {

	private Integer nuGrupoAcesso;
	private String noGrupoAcesso;
	private Set<Ofbtb002Usuario> ofbtb002Usuarios = new HashSet<Ofbtb002Usuario>(0);

	public Ofbtb001GrupoAcesso() {
	}

	public Ofbtb001GrupoAcesso(String noGrupoAcesso) {
		this.noGrupoAcesso = noGrupoAcesso;
	}

	public Ofbtb001GrupoAcesso(String noGrupoAcesso, Set<Ofbtb002Usuario> ofbtb002Usuarios) {
		this.noGrupoAcesso = noGrupoAcesso;
		this.ofbtb002Usuarios = ofbtb002Usuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@SequenceGenerator(name = "grupo_gen", schema = "OFB", sequenceName = "OFBSQ001_NU_GRUPO_ACESSO", initialValue = 1, allocationSize = 0)
	@Column(name = "NU_GRUPO_ACESSO", unique = true, nullable = false, precision = 5, scale = 0, columnDefinition="DECIMAL(5)")
	public Integer getNuGrupoAcesso() {
		return this.nuGrupoAcesso;
	}

	public void setNuGrupoAcesso(Integer nuGrupoAcesso) {
		this.nuGrupoAcesso = nuGrupoAcesso;
	}

	@Column(name = "NO_GRUPO_ACESSO", unique = true, nullable = false, length = 50)
	public String getNoGrupoAcesso() {
		return this.noGrupoAcesso;
	}

	public void setNoGrupoAcesso(String noGrupoAcesso) {
		this.noGrupoAcesso = noGrupoAcesso;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "ofbtb001GrupoAcesso")
	public Set<Ofbtb002Usuario> getOfbtb002Usuarios() {
		return this.ofbtb002Usuarios;
	}

	public void setOfbtb002Usuarios(Set<Ofbtb002Usuario> ofbtb002Usuarios) {
		this.ofbtb002Usuarios = ofbtb002Usuarios;
	}

	@Override
	public String toString() {
		return "Ofbtb001GrupoAcesso [nuGrupoAcesso=" + nuGrupoAcesso + ", noGrupoAcesso=" + noGrupoAcesso + "]";
	}
	
}
